---
title: "projekt_BI"
format: html
---

```{r}
#install.packages("haven")
#install.packages("tidyverse")
#install.packages("nonprobsvy")
```


```{r}
library(readxl)
library(haven)
library(nonprobsvy)
library(dplyr)
```

```{r}
dane_bkl <- read_sav("Poczona_baza_danych_z_badania_ludnoci_z_lat_20172019_i_2021.sav")
#zmienna y1 odsetek osób pracujących za granicą 
```


```{r}
attr(dane_bkl$e1, "labels")
table(as_factor(dane_bkl$e1), useNA = "ifany")
```

```{r}
dane_bkl$Y <- ifelse(dane_bkl$e1 == 1, 1,
                         ifelse(dane_bkl$e1 == 0, 0, NA))

table(dane_bkl$Y, useNA = "ifany")
prop.table(table(dane_bkl$Y)) * 100
#Tylko ok 3,58% respondentów ma pracowało zarobkowo zagranicą w ciągu ostatnich 12 miesięcy
```

```{r}
table(dane_bkl$rok, dane_bkl$e1, useNA = "ifany")
prop.table(table(dane_bkl$rok, dane_bkl$e1), margin = 1) * 100
# Wartość zmiennej w poszczególnych latach
```

```{r}
# Poprawiona zmienna woj_operat
dane_bkl$woj_raw <- as.numeric(dane_bkl$woj_operat)

dane_bkl$woj_idx <- ifelse(
  dane_bkl$rok == 2017,
  dane_bkl$woj_raw,
  dane_bkl$woj_raw / 2
)

dane_bkl$woj_clean <- factor(
  dane_bkl$woj_idx,
  levels = 1:16
)

table(dane_bkl$rok, dane_bkl$woj_clean, useNA = "ifany")
```
```{r}
table(as_factor(dane_bkl$g2_3), useNA = "ifany")
```


```{r}
dane_bkl$umiej <- case_when(
  as_factor(dane_bkl$g2_3) %in% c("zdecydowanie nie", "raczej nie") ~ "nie",
  as_factor(dane_bkl$g2_3) %in% c("raczej tak", "zdecydowanie tak") ~ "tak",
  as_factor(dane_bkl$g2_3) == "trudno powiedzieć" ~ "trudno powiedzieć",
  as_factor(dane_bkl$g2_3) == "odmowa odpowiedzi" ~ "odmowa",
  as_factor(dane_bkl$g2_3) %in% c("brak danych", "NDT") ~ NA_character_,
  TRUE ~ NA_character_
)

dane_bkl$umiej <- factor(dane_bkl$umiej,levels = c("nie", "trudno powiedzieć", "tak", "odmowa"))
```

```{r}
dane_bkl$jez <- case_when(
  as_factor(dane_bkl$w9_1) %in% c("inny język", "łacina", "czeski", "holenderski, niderlandzki", "ukraiński", "białoruski", "grecki", "szwedzki", "norweski", "japoński", "romski", "chorwacki", "słowacki") ~ "inny",
  as_factor(dane_bkl$w9_1) %in% c("francuski", "hiszpański", "włoski") ~ "romański",
  as_factor(dane_bkl$w9_1) == "niemiecki" ~ "niemiecki",
  as_factor(dane_bkl$w9_1) == "rosyjski" ~ "rosyjski",
    as_factor(dane_bkl$w9_1) == "angielski" ~ "angielski",
  as_factor(dane_bkl$w9_1) %in% c("brak danych", "NDT") ~ NA_character_,
  TRUE ~ NA_character_
)

dane_bkl$jez <- factor(dane_bkl$jez, levels = c("inny", "romański", "niemiecki", "rosyjski", "angielski"))
```


Wybrane zmienne 
woj_opetat --> woj_clean
miejsce_4k
wiek_4k
g2_3 --> umiej (Podniósł umiejętności w ciągu ost. 5 lat)
k24 (gotowość do częstych wyjazdów)
w9_1 --> jez (jezyk obcy 1)
```{r}
vars <- c("wiek_4k", "miejsce_4k", "woj_clean", "umiej", "k24", "jez")
```

```{r}
wyniki <- data.frame()

for (v in vars) {
  
  x <- dane_bkl[[v]]
  
  if (inherits(x, "haven_labelled")) {
    x <- as_factor(zap_missing(x))
  } else {
    x <- factor(x)
  }
  
  tmp <- data.frame(
    x = x,
    Y = dane_bkl$Y
  )
  
  tmp <- na.omit(tmp)
  tmp$x <- droplevels(tmp$x)
  tmp$Y <- droplevels(factor(tmp$Y))
  
  tab <- table(tmp$x, tmp$Y)
  
  test <- suppressWarnings(chisq.test(tab, correct = FALSE))
  
  chi2 <- as.numeric(test$statistic)
  n <- sum(tab)
  V <- sqrt(chi2 / (n * (min(dim(tab)) - 1)))
  
  wyniki <- rbind(wyniki, data.frame(
    zmienna = v,
    V_Cramera = round(V, 3),
    p_value = signif(test$p.value, 4),
    kategorie = nrow(tab),
    n = n
  ))
}


wyniki
```

WYBRANE ZMIENNE
woj_clean
miejsce_4k
wiek_4k
umiej (Podniósł umiejętności w ciągu ost. 5 lat)
k24 (gotowość do częstych wyjazdów)
jez (jezyk obcy 1)

```{r}
dane <- dane_bkl %>% select(e1, woj_clean, miejsce_4k, wiek_4k, umiej, k24, jez) 
head(dane)
```


```{r}
# LOSOWANIE PROSTE
set.seed(123)

proba <- dane[
  sample(1:nrow(dane), size = 1000),
]
```


