---
title: "projekt_BI"
format: html
---

```{r}
#install.packages("haven")
#install.packages("tidyverse")
#install.packages("nonprobsvy")
```


```{r}
library(readxl)
library(haven)
library(nonprobsvy)
library(dplyr)
#library(data.table)
#library(sjplot)
```

```{r}
dane_bkl <- read_sav("../dane-surowe/proj_bi/Poczona_baza_danych_z_badania_ludnoci_z_lat_20172019_i_2021.sav")
#zmienna y1 odsetek osób pracujących za granicą 
```


```{r}
attr(dane_bkl$y1, "labels")
table(dane_bkl$y1, useNA = "ifany")
table(as_factor(dane_bkl$y1), useNA = "ifany")
```

```{r}
dane_bkl$Y_praca_zagranica <- ifelse(dane_bkl$y1 == 1, 1,
                         ifelse(dane_bkl$y1 == 0, 0, NA))
table(dane_bkl$Y_praca_zagranica, useNA = "ifany")
prop.table(table(dane_bkl$Y_praca_zagranica)) * 100
#Tylko ok 3,58% respondentów ma pracowało zarobkowo zagranicą w ciągu ostatnich 12 miesięcy
```
```{r}
table(dane_bkl$rok, dane_bkl$y1, useNA = "ifany")
prop.table(table(dane_bkl$rok, dane_bkl$y1), margin = 1) * 100
# Wartość zmiennej w poszczególnych latach
```

Wybrane zmienne 
woj_opetat --> woj_clean
miejsce
wiek_4K
g2_3 (Podniósł umiejętności w ciągu ost. 5 lat)
k24 (gotowość do częstych wyjazdów)
w9_1 (jezyk obcy 1)



```{r}
woj_levels <- c(
  "dolnośląskie",
  "kujawsko-pomorskie",
  "lubelskie",
  "lubuskie",
  "łódzkie",
  "małopolskie",
  "mazowieckie",
  "opolskie",
  "podkarpackie",
  "podlaskie",
  "pomorskie",
  "śląskie",
  "świętokrzyskie",
  "warmińsko-mazurskie",
  "wielkopolskie",
  "zachodniopomorskie"
)

dane_bkl <- dane_bkl %>%
  mutate(
    woj_raw = as.numeric(woj_operat),
    
    woj_idx = case_when(
      rok == 2017 & woj_raw %in% 1:16 ~ woj_raw,
      rok %in% c(2019, 2021, 2022) & woj_raw %in% seq(2, 32, 2) ~ woj_raw / 2,
      TRUE ~ NA_real_
    ),
    
    woj_clean = factor(
      woj_levels[woj_idx],
      levels = woj_levels
    )
  )
table(dane_bkl$rok, dane_bkl$woj_clean, useNA = "ifany")
```
```{r}
vars_x <- c("woj_clean", "miejsce", "wiek_4k", "g2_3", "k24", "w9_1")
# Etykiety zmiennych
sapply(dane_bkl[vars_x], function(x) attr(x, "label"))

# Kody odpowiedzi
lapply(dane_bkl[vars_x], function(x) attr(x, "labels"))
```

```{r}
wyniki <- data.frame()

for (v in vars) {
  
  x <- dane_bkl[[v]]
  if (inherits(x, "haven_labelled")) x <- as_factor(x)
  
  y <- dane_bkl$Y
  
  ok <- complete.cases(x, y)
  tab <- table(x[ok], y[ok])
  
  test <- suppressWarnings(chisq.test(tab, correct = FALSE))
  
  chi2 <- as.numeric(test$statistic)
  n <- sum(tab)
  V <- sqrt(chi2 / (n * (min(dim(tab)) - 1)))
  
  wyniki <- rbind(
    wyniki,
    data.frame(
      zmienna = v,
      kategorie = nrow(tab),
      n = n,
      chi2 = round(chi2, 3),
      p_value = signif(test$p.value, 4),
      V_Cramera = round(V, 3),
      min_oczekiwana = round(min(test$expected), 3),
      proc_komorek_ponizej_5 = round(mean(test$expected < 5) * 100, 1)
    )
  )
}

wyniki <- wyniki %>% arrange(desc(V_Cramera))
wyniki
```







